import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Google フォント（Next.js の next/font 経由）
 * 変数名を指定して CSS 変数として利用できるようにしています。
 * これにより各モジュールで `var(--font-geist-sans)` 等を参照可能。
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * ページメタ情報（SEO 等に利用）
 * 必要ならタイトルや description をプロジェクト向けに書き換えてください。
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout
 * - 全ページのルートレイアウト
 * - globals.css を読み込んでいるためここでフォント変数を body に適用しています
 * - children は各ページの内容（Next.js の App Router の仕組み）
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* フォント変数を body に適用し、アンチエイリアスを有効化 */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
